package org.hcjf.cloud.memory;

import org.hcjf.service.Service;
import org.hcjf.service.ServiceConsumer;

import java.util.Map;
import java.util.Queue;

/**
 * This service provides an interface to use a cloud memory
 * service over the service instances.
 * @author javaito
 * @mail javaito@gmail.com
 */
public abstract class SharedMemory extends Service<SharedMemory.SharedMemoryConsumer> {

    protected static final String SHARED_MEMORY_LOG_TAG = "SHARED_MEMORY";
    private static final String SHARED_MEMORY_SERVICE_NAME = "Shared Memory";

    public SharedMemory() {
        super(SHARED_MEMORY_SERVICE_NAME);
    }

    /**
     * This method register the consumer in the service.
     *
     * @param consumer Object with the logic to consume the service.
     * @throws RuntimeException It contains exceptions generated by
     *                          the particular logic of each implementation.
     */
    @Override
    public void registerConsumer(SharedMemoryConsumer consumer) {
        consumer.setMemory(this);
    }

    /**
     * Get an instance of the distributed map from the cloud. This object
     * is synchronized with all the instances of the service in the cloud.
     * @param memoryName Map's name.
     * @param <K> Map's key type.
     * @param <V> Map's value type.
     * @return Return the distributed instance.
     */
    protected abstract <K extends Object, V extends Object> Map<K, V> getMap(String memoryName);

    /**
     *
     * @param memoryName
     * @param <V>
     * @return
     */
    protected abstract <V extends Object> Queue<V> getQueue(String memoryName);

    public static class SharedMemoryConsumer implements ServiceConsumer {

        private SharedMemory memory;

        private SharedMemoryConsumer() {
        }

        private void setMemory(SharedMemory memory) {
            this.memory = memory;
        }

        public final <K extends Object, V extends Object> Map<K, V> getMap(String memoryName) {
            if(memory == null) {
                throw new IllegalStateException("Consumer is not registered");
            }
            return memory.getMap(memoryName);
        }

        public final <V extends Object> Queue<V> getQueue(String memoryName) {
            if(memory == null) {
                throw new IllegalStateException("Consumer is not registered");
            }
            return memory.getQueue(memoryName);
        }
    }
}
